### ISSUE TITLE
chore: How to access Gradle

### ISSUE THREAD

**Issue by mendesbarreto** [saschpe/docker-android-ndk#16]
Hi,

How's it going?

I'm not an expert in Android development, but I want to build my Android project using the gradle build command on this image. Is it accessible? 

Currently, I'm installing it via sdkman: https://sdkman.io/. I was wondering if it's already set up. =)

thank you for your time.

**Comment by saschpe** [comment]
Almost all Android projects use the Gradle wrapper to bootstrap. This images has the JDK and Androis SDKs. If you set up your project with Android Studio or IntelliJ, it will utilize the Gradle wrapper.
